use std::sync::Arc;
use tokio::sync::Mutex;

pub async fn handle_help(output_lines: &Arc<Mutex<Vec<String>>>) {
    let lines = get_help_lines();
    let mut out = output_lines.lock().await;
    out.extend(lines);
}

fn get_help_lines() -> Vec<String> {
    vec![
        "help                  - Show this help message".to_string(),
        "http start|stop       - Control HTTP/web services".to_string(),
        "debug [module] [level]- Set debug level (error, warn, info, debug, trace)".to_string(),
        "status                - Show system status".to_string(),
        "services              - List all available services".to_string(),
        "version               - Show SAM version information".to_string(),
        "errors                - Show/hide error output in CLI".to_string(),
        "clear                 - Clear the terminal screen".to_string(),
        "exit, quit            - Exit the command prompt".to_string(),
        "ls                    - List files in current directory".to_string(),
        "pwd                   - Print current working directory".to_string(),
        "cd <dir>              - Change current directory".to_string(),
        "mkdir <dir>           - Create directories (supports -p for parent directories)".to_string(),
        "rmdir <dir>           - Remove empty directories".to_string(),
        "cp <src> <dest>       - Copy files or directories (supports -r for recursive)".to_string(),
        "mv <src> <dest>       - Move/rename files or directories".to_string(),
        "rm <file>             - Remove files or directories (supports -r for recursive, -f for force)".to_string(),
        "cat <file>            - Display file contents (supports -n, -v, -s options)".to_string(),
        "less <file>           - View file with paging (j/k scroll, g/G start/end, q quit)".to_string(),
        "                       Navigation: Use scroll offset commands or re-run with adjusted view".to_string(),
        "nano [file]           - Open text editor (Ctrl+X: exit, Ctrl+O: save, Ctrl+G: help)".to_string(),
        "touch <file>          - Create empty files or update timestamps (supports -c, -t)".to_string(),
        "head [-n lines] <file> - Show first N lines of files (default: 10)".to_string(),
        "tail [-n lines] <file> - Show last N lines of files (default: 10, supports -f)".to_string(),
        "find <path> [options] - Search for files and directories".to_string(),
        "                       Options: -name pattern, -type f|d, -maxdepth N".to_string(),
        "chmod <mode> <file>   - Change file permissions (octal or symbolic: u+x,g-w,o=r)".to_string(),
        "chown <owner> <file>  - Change file ownership (Unix/Linux only)".to_string(),
        "grep <pattern> [files] - Search for pattern in files (supports -i, -n, -v, -r, -c, -l)".to_string(),
        "                       Can be used in pipes: cat file | grep pattern".to_string(),
        "echo [-n] [-e] [text]  - Display a line of text (supports -n: no newline, -e: escape sequences)".to_string(),
        "sort [-r] [-u] [-n] [-f] [files] - Sort lines of text files".to_string(),
        "                       Options: -r (reverse), -u (unique), -n (numeric), -f (ignore case)".to_string(),
        "wc [-l] [-w] [-c] [files] - Count lines, words, and characters in files".to_string(),
        "                       Options: -l (lines), -w (words), -c (characters)".to_string(),
        "tar [-c|-x|-t] [-f archive] [files] - Archive and extract files".to_string(),
        "                       Options: -c (create), -x (extract), -t (list), -f (file), -v (verbose), -z (gzip)".to_string(),
        "gzip [-d] [-c] [-f] [-v] [files] - Compress or decompress files".to_string(),
        "                       Options: -d (decompress), -c (stdout), -f (force), -v (verbose)".to_string(),
        "gunzip [-c] [-f] [-v] [files] - Decompress gzip files (same as gzip -d)".to_string(),
        "<cmd1> | <cmd2>        - Pipe output from cmd1 to cmd2 (supports grep, head, tail, wc, sort, uniq, echo)".to_string(),
        "tts <text>            - Convert text to speech and play it".to_string(),
        "llama install         - Install or update Llama.cpp models".to_string(),
        "llama <prompt>        - Query default Llama model (tinyllama-1.1b-chat-v1.0)".to_string(),
        "llama <model_path> <prompt> - Query a specific Llama.cpp model".to_string(),
        "llama2 <prompt>       - Query a Llama v2 model".to_string(),
        "llama2-tiny <prompt>  - Query a Llama v2-tiny model".to_string(),
        "lifx start            - Start the LIFX service".to_string(),
        "lifx stop             - Stop the LIFX service".to_string(),
        "lifx status           - Show LIFX service status".to_string(),
        "crawler start           - Start the background web crawler".to_string(),
        "crawler stop            - Stop the background web crawler".to_string(),
        "crawler status          - Show crawler service status".to_string(),
        "crawl search <query>   - Search crawled pages for a keyword".to_string(),
        "redis install           - Install Redis using Docker".to_string(),
        "redis start             - Start the Redis Docker container".to_string(),
        "redis stop              - Stop the Redis Docker container".to_string(),
        "redis status            - Show Redis Docker container status".to_string(),
        "docker start             - Start the Docker daemon/service".to_string(),
        "docker stop              - Stop the Docker daemon/service".to_string(),
        "docker status            - Show Docker daemon/service status".to_string(),
        "spotify start             - Start Spotify playback service".to_string(),
        "spotify stop              - Stop Spotify playback service".to_string(),
        "spotify status            - Show Spotify playback status".to_string(),
        "spotify play              - Resume Spotify playback".to_string(),
        "spotify pause             - Pause Spotify playback".to_string(),
        "spotify shuffle           - Toggle Spotify shuffle mode".to_string(),
        "".to_string(),
        "═══ System Information Commands ═══".to_string(),
        "uname [options]           - Display system information".to_string(),
        "                           Options: -a (all), -s (kernel), -n (nodename), -r (release), -v (version), -m (machine), -o (OS)".to_string(),
        "whoami                    - Display current username".to_string(),
        "date [options] [+format]  - Display or format current date and time".to_string(),
        "                           Options: -u/--utc (UTC time), +FORMAT (custom format)".to_string(),
        "df [options]              - Display filesystem disk space usage".to_string(),
        "                           Options: -h (human-readable), -T (show type), -i (inodes)".to_string(),
        "du [options] [path]       - Display disk usage of files and directories".to_string(),
        "                           Options: -h (human-readable), -s (summarize), --max-depth=N".to_string(),
        "".to_string(),
        "═══ Process Control Commands ═══".to_string(),
        "ps [options]              - Display running processes".to_string(),
        "                           Options: -a (all users), -f (full format), -T (threads), aux (BSD style)".to_string(),
        "top                       - Display dynamic view of running processes (snapshot)".to_string(),
        "kill [-signal] pid...     - Send signal to processes (default: TERM)".to_string(),
        "kill -l                   - List available signals".to_string(),
        "".to_string(),
        "═══ Documentation ═══".to_string(),
        "man <command>             - Display manual page for command".to_string(),
        "                           Available: uname, whoami, ps, top, kill, date, df, du".to_string(),
    ]
}
